DROP EVENT IF EXISTS AUTO_DELETE_TOKEN;

CREATE EVENT AUTO_DELETE_TOKEN  ON SCHEDULE EVERY 1 HOUR
    STARTS '2010-01-01 00:00:00'
    DO
    DELETE FROM oopdb.TOKENS where DATEDIFF(now(), DateAdded) > 1;

ALTER EVENT AUTO_DELETE_TOKEN ON  COMPLETION PRESERVE ENABLE;